travis:
  secure:
    BINSTAR_TOKEN: LnU9Ab7qCCb/kzJ3zCfoCzSGL/0p5yOK2xKqwfI+gMCeCyGUJiYRnBYJmj8NxPgcRKewJD+0UJEQvMJekEgNo8P4VYv89LkZhsS2nPTVXhQP/QJzPltu/kabQatKTlL2yVSYNwgExWqLKOZR2DLEg71+q5kpvHxCbq2shAmkVML7uuX5OSnw8w06YXcLo38KYmd9swppHXRxL3mg/W/TrmzW39TUmn3P9KheLTbGp63ZztrCq/xKYjrhJc/n4o9NDagUsTUiq0h+4RDKWGm2kqrEVxAYyKafJrgKwW41f7wsMGxSRPB1PE4e47zxRdxvW44bkwwYeSZDziwnFVd+62rjHMuu+Fl69GK2RMesr7dPeybJ/MV6FLSLRxmvFGrqC9wveXmplwlenjbQCQ7OQ+sg8QpoDHNIxxlmMPjfL7x0Up/Pv8ZiiHG9dLPNj72VKajmzxpPk2asKibtqSYFvPyjlzGZpg+uAzC/4fpL+I/8kRlZh+sWHzXWv13/1CaLQtOMiksLPuZ0gfKSS/+3tZP9Ioo+9DnCF/c/nfpDO4CTz5jecCXhQ10RgEh/ymzP6xrT7JBlyGmOcYHnRlpIuNiuw6wphNYR/+pAPc274xvsFa496Nw9dp/O4cM7SYXR1+ksoTSjkxCORGgUgaM2lRaMlPWPqimkpIKZWpxym6Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
