travis:
  secure:
    BINSTAR_TOKEN: f+KAN/wGEkjzXqzzYAr2gTuw38iejGOXSWeIGB/yf/oBpEbN4xoxe10hMGgG147MhdOXkMZfnzuIoM05n3aBJDcZWPY362ZgCK7OtEXX1UNoSt63YYpwNY59kzQFld6BV6EnUMJk4Il+sP8pArcka3KDgCOhvUIgj8JJM96ibaunM9+fCknV2GbA2mqjuplEgMcISnQrs1OuzOonq2mV0UdwrDWo0RbJAdnAUE8yDERuBtfKaoEsRYhpr/DzPfwZm/BQEGlLuO7RLzbkJrPpP9Oy1JFxnYpI25+L8QWWdoPLB2as+S8jXQlp+AGb1z24DEZ3NYgb0QFBGRSMb0nkTSNcQG9FDcMnu9Xt8CgPfdJM6V0GJGg1S14oiHS5vRIPR399v3izC4rvlIT5PaGBw92PnUgrFvJ2u3xT9FfUPh+GNatjPsxZ2gz0nLuMS/VTuXKyp/3gr6GUmKnXrYuGNPPXY89cyNUcy5EDlbPRxA6Ky+HYAhmgY9EwXXnP3gZbDSANhok976DaVE5YuLjvM9dsQfzBcXSalhwVP0XcQNy/y18H77LaWaRBdYboNlRy4SjMGLFPzp/j9xMTnrGB7Pq2RerELee4+phr3BPW+PxlHin80MyBSfXe3JxhPrb7+qLmRtAV/QNkK1WzigcIHLPG+lUsVNmU2+dTSszK53w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
